BuildingFacilityManager/Models/Tasks/Enums/InspectionStatus.cs
using System.ComponentModel.DataAnnotations;

namespace BuildingFacilityManager.Models.Tasks.Enums
{
    public enum InspectionStatus
    {
        Active = 1,
        Paused = 2,
        Completed = 3,
        [Display(Name = "Partially Completed")]
        PartiallyCompleted = 4
    }
}

BuildingFacilityManager/Models/Tasks/Enums/InspectionType.cs
using System.ComponentModel.DataAnnotations;

namespace BuildingFacilityManager.Models.Tasks.Enums
{
    public enum InspectionType
    {
        [Display(Name = "Location Inspection")]
        LocationInspection = 1,

        [Display(Name = "Generator Inspection")]
        GeneratorInspection = 2,

        [Display(Name = "Pump Inspection")]
        PumpInspection = 3,

        [Display(Name = "FireFighting Inspection")]
            FireFightingInspection = 4,

        [Display(Name = "AirConditioning Inspection")]
            AirConditioningInspection = 5

    }
}

BuildingFacilityManager/Models/Tasks/Enums/PeriodicInspection.cs
namespace BuildingFacilityManager.Models.Tasks.Enums
{
    public enum PeriodicInspection
    {
        Daily = 1,
        Weekly = 2,
        //Monthly = 3,

    }
}

BuildingFacilityManager/Models/Tasks/InspectionTask.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using BuildingFacilityManager.Models.Building_Models;
using BuildingFacilityManager.Models.Tasks.Enums;

namespace BuildingFacilityManager.Models.Tasks
{
    public class InspectionTask
    {
        public int Id { get; set; }
        [Required]
        public string Description { get; set; }

        public ApplicationUser Inspector { get; set; }

        [ForeignKey("Inspector")]
        public string InspectorId { get; set; }

        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
       

        public InspectionStatus? InspectionStatus { get; set; }
        public PeriodicInspection? PeriodicInspection { get; set; }
        public InspectionType? InspectionType { get; set; }

        public Storey StoreyInspection { get; set; }
        [ForeignKey("StoreyInspection")]
        [Display(Name = "Location")]
        public int? StoreyInspectionId { get; set; }

        public string InspectionNotes { get; set; }


        /*  This is for Emergency Assets like the Elevator and Plumping ... etc  */
        // public SpecialAsset SpecialAsset { get; set;} 



    }
}

BuildingFacilityManager/ViewModels/TaskViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BuildingFacilityManager.Models;
using BuildingFacilityManager.Models.Building_Models;
using BuildingFacilityManager.Models.Tasks;

namespace BuildingFacilityManager.ViewModels
{
    public class TaskViewModel
    {
        public InspectionTask InspectionTask { get; set; }
        public ICollection<InspectionTask> TodayInspectionTasks { get; set; }
        public ICollection<InspectionTask> ScheduledInspectionTasks { get; set; }
        public ICollection<InspectionTask> ActiveInspectionTasks { get; set; }
        public ICollection<InspectionTask> CompletedInspectionTasks { get; set; }
        public ICollection<InspectionTask> PausedInspectionTasks { get; set; }

        public ICollection<ApplicationUser> Inspectors { get; set; }
        public ApplicationUser Inspector { get; set; }

        public ICollection<Storey> Stories { get; set; }
        public Storey Storey { get; set; }
    }
}

BuildingFacilityManager/Areas/Admin/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuildingFacilityManager.Models;
using BuildingFacilityManager.Models.Tasks;
using BuildingFacilityManager.Models.Tasks.Enums;
using BuildingFacilityManager.ViewModels;

namespace BuildingFacilityManager.Areas.Admin.Controllers
{
    public class TaskController : AdminAuthorizationController
    {
        private readonly ApplicationDbContext _context;

        public TaskController()
        {
            _context = new ApplicationDbContext();
        }


        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            _context.Dispose();
        }


        public ActionResult Index()
        {
            var today = DateTime.Today;
            var todayLastWeek = today.AddDays(-7);
            //var todayLastWeek = today.(-7);
            var tomorrow = today.AddDays(1);
            var yesterday = today.AddDays(-1);

            var taskModel = new TaskViewModel()
            {
                TodayInspectionTasks = _context.InspectionTasks
                    .Where(t =>
                         DbFunctions.TruncateTime(t.StartDate)
                            == DbFunctions.TruncateTime(today)
                                //t => t.StartDate >= today && t.StartDate < tomorrow
                                ||
                         DbFunctions.TruncateTime(today)
                         <= DbFunctions.TruncateTime(t.EndDate) &&
                         DbFunctions.TruncateTime(today)
                         >= DbFunctions.TruncateTime(t.StartDate)
                         /*  today <= t.EndDate && today >= t.StartDate */
                         && t.PeriodicInspection == PeriodicInspection.Daily


                                ||

                                // Stupid Code starts from Here !

                                today.Day == (t.StartDate.Value.Day + 7) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                                ||
                                today.Day == (t.StartDate.Value.Day + 14) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                                ||
                                today.Day == (t.StartDate.Value.Day + 21) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                                ||
                                today.Day == (t.StartDate.Value.Day + 28) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                                )

                    .Include(t => t.Inspector)
                    .Include(t => t.StoreyInspection)
                    .ToList(),

                ScheduledInspectionTasks = _context.InspectionTasks
                    .Where(t => t.StartDate >= tomorrow)
                    .Include(t => t.Inspector)
                    .Include(t => t.StoreyInspection)
                    .ToList(),

                PausedInspectionTasks = _context.InspectionTasks
                    .Where(t => t.InspectionStatus == InspectionStatus.Paused)
                    .Include(t => t.Inspector)
                    .Include(t => t.StoreyInspection)
                    .ToList(),

                CompletedInspectionTasks = _context.InspectionTasks
                    .Where(t => t.InspectionStatus == InspectionStatus.Completed)
                    .Include(t => t.Inspector)
                    .Include(t => t.StoreyInspection)
                    .ToList(),

                Inspectors = _context.Users.Where(u => u.Roles.Any(r => r.RoleId == "2")).ToList(),

                Stories = _context.Stories.ToList()

            };

            return View(taskModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddInspectionTask(InspectionTask inspectionTask)
        {
            if (inspectionTask.InspectorId != null && inspectionTask.Description != null
                                                   && inspectionTask.InspectionStatus != 0
                                                   && inspectionTask.StartDate != null)
            {
                _context.InspectionTasks.Add(inspectionTask);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeInspectionTaskStatus(InspectionTask inspectionTask)
        {
            var mytask = _context.InspectionTasks.SingleOrDefault(w => w.Id == inspectionTask.Id);
            if (mytask != null && inspectionTask.InspectionStatus != 0) mytask.InspectionStatus = inspectionTask.InspectionStatus;

            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BuildingFacilityManager/Areas/Inspector/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuildingFacilityManager.Models;
using BuildingFacilityManager.Models.Tasks;

namespace BuildingFacilityManager.Areas.Inspector.Controllers
{
    public class TaskController : InspectorAuthorizationController
    {
        private readonly ApplicationDbContext _context;

        public TaskController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ChangeInspectionTaskStatus(InspectionTask inspectionTask)
        {
            var mytask = _context.InspectionTasks.SingleOrDefault(w => w.Id == inspectionTask.Id);
            if (mytask != null && inspectionTask.InspectionStatus != 0) mytask.InspectionStatus = inspectionTask.InspectionStatus;
            if (mytask != null && inspectionTask.InspectionNotes != null) mytask.InspectionNotes = inspectionTask.InspectionNotes;


            _context.SaveChanges();
            return RedirectToAction("Index","Dashboard");
        }
    }
}

BuildingFacilityManager/Areas/Admin/Views/Task/AddTasks_Partial.cshtml
@using BuildingFacilityManager.Models.Tasks.Enums
@model BuildingFacilityManager.ViewModels.TaskViewModel

@{

    using (Ajax.BeginForm("AddInspectionTask", "Task", new AjaxOptions()
    {
        Confirm = "Are you Sure ?",
        HttpMethod = "Post",
        OnSuccess = "$('.close').click();"

    }))
    {


        <div class="modal fade" id="Add-Task" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Add a new Task</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            @Html.HiddenFor(s => s.InspectionTask.Id)

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(e => e.InspectionTask.Description)
                            @Html.TextAreaFor(e => e.InspectionTask.Description, new { @class = "form-control", style = "width: 100%; max-width: 100%;" })
                            @Html.ValidationMessageFor(e => e.InspectionTask.Description)

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(e => e.InspectionTask.InspectorId)
                            @Html.DropDownListFor(c => c.InspectionTask.InspectorId, new SelectList(@Model.Inspectors, "Id", "Fullname"), "Select an Inspector", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.InspectionTask.InspectorId)

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(e => e.InspectionTask.InspectionStatus)
                            @Html.DropDownListFor(e => e.InspectionTask.InspectionStatus, EnumHelper.GetSelectList(typeof(InspectionStatus)) ,
                                "Select Type", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.InspectionTask.InspectionStatus)

                        </div>
                        <div class="form-group">
                            @Html.LabelFor(e => e.InspectionTask.StartDate)
                            @Html.TextBoxFor(c => c.InspectionTask.StartDate, new { @class = "datepicker form-control", @type = "datetime-local" })
                            @Html.ValidationMessageFor(e => e.InspectionTask.StartDate)

                        </div>
                        <div class="form-group">
                            @Html.LabelFor(e => e.InspectionTask.EndDate)
                            @Html.TextBoxFor(c => c.InspectionTask.EndDate, new { @class = "datepicker form-control", @type = "datetime-local" })
                            @Html.ValidationMessageFor(e => e.InspectionTask.EndDate)

                        </div>
                        <div class="form-group">
                            @Html.LabelFor(e => e.InspectionTask.PeriodicInspection)
                            @Html.DropDownListFor(e => e.InspectionTask.PeriodicInspection, EnumHelper.GetSelectList(typeof(PeriodicInspection)) ,
                                "Select Type", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.InspectionTask.PeriodicInspection)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(e => e.InspectionTask.InspectionType)
                            @Html.DropDownListFor(e => e.InspectionTask.InspectionType, EnumHelper.GetSelectList(typeof(InspectionType)) ,
                                "Select Type", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.InspectionTask.InspectionType)
                        </div>
                        
                        <div class="form-group">
                            @Html.LabelFor(e => e.InspectionTask.StoreyInspectionId)
                            @Html.DropDownListFor(c => c.InspectionTask.StoreyInspectionId, new SelectList(@Model.Stories, "Id", "Label"), "Select an Location", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.InspectionTask.StoreyInspectionId)

                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Add" class="btn btn-primary" />
                </div>
            </div>

        </div>

    }
}



@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    
   
}

BuildingFacilityManager/Areas/Admin/Views/Task/ChangeTaskStatus_Partial.cshtml
@using BuildingFacilityManager.Models.Tasks.Enums
@model BuildingFacilityManager.ViewModels.TaskViewModel

@{

    using (Html.BeginForm("ChangeInspectionTaskStatus", "Task", new AjaxOptions()
    {
        HttpMethod = "Post",
        OnSuccess = "$('.close').click();"

    }))
    {


        <div class="modal fade" id="Change-Status" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Change Task Status</h4>
                    </div>
                    <div class="modal-body">
                        <input id="task-Id-Status" name="InspectionTask.Id" type="hidden" value="">

                        <div>
                            @Html.LabelFor(e => e.InspectionTask.InspectionStatus)
                            @Html.DropDownListFor(e => e.InspectionTask.InspectionStatus, EnumHelper.GetSelectList(typeof(InspectionStatus)) ,
                                "Select Type", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.InspectionTask.InspectionStatus)

                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Change Status" class="btn btn-primary" />
                </div>
            </div>

        </div>

    }
}



<script>
    let statusId;

    function TaskIdForStatusChange(id) {
        statusId = id;
        document.getElementById("task-Id-Status").value = statusId;

    }
</script>

BuildingFacilityManager/Areas/Admin/Views/Task/CompletedTasks_Partial.cshtml
@model BuildingFacilityManager.ViewModels.TaskViewModel

<h3>Completed Tasks</h3>

<div class="thumbnail">

    <div class="caption">
        <table class="table table-hover table-bordered" id="CompletedTasksTable">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Description</th>
                    <th>Inspector</th>
                    <th>Status</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Periodic Inspection</th>
                    <th>Inspection Type</th>
                    <th>Location</th>
                    <th>Inspection Notes</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var task in Model.CompletedInspectionTasks)
                {

                    <tr id="id-@task.Id">

                        <td>
                            @task.Id
                        </td>
                        <td>
                            @task.Description
                        </td>
                        <td>
                            @{
                                if (task.Inspector != null)
                                {
                                    @task.Inspector.Fullname

                                }

                            }
                        </td>
                        <td>
                            @task.InspectionStatus

                        </td>
                        <td>
                            @task.StartDate
                        </td>
                        <td>
                            @task.EndDate
                        </td>
                        <td>
                            @task.PeriodicInspection
                        </td>
                        <td>
                            @task.InspectionType
                        </td>
                        <td>
                            @{
                                if (@task.StoreyInspection != null)
                                {
                                    @task.StoreyInspection.Label

                                }

                            }
                        </td>
                        <td>
                            @task.InspectionNotes
                        </td>
                       
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BuildingFacilityManager/Areas/Admin/Views/Task/Index.cshtml
@model BuildingFacilityManager.ViewModels.TaskViewModel
@{
    ViewBag.Title = "Tasks";
    Layout = "../Shared/_Layout.cshtml";
}

<br />
<br />
<button type="button" class="btn btn-success" style="float: right" data-toggle="modal" data-target="#Add-Task">
    Add
</button>



@Html.Partial("TodaysTasks_Partial")
<br />
<hr />
@Html.Partial("ScheduledTasks_Partial")
<br />
<hr />
@Html.Partial("CompletedTasks_Partial")
<br />
<hr />
@Html.Partial("PausedTasks_Partial")
@Html.Partial("AddTasks_Partial")
@Html.Partial("ChangeTaskStatus_Partial")



@section scripts
{
    <script>

        $(document).ready(function () {
            $("#TodayTasksTable").DataTable();
            $("#ScheduledTasksTable").DataTable();
            $("#CompletedTasksTable").DataTable();
            $("#PausedTasksTable").DataTable();
        });

      
    </script>
}

BuildingFacilityManager/Areas/Admin/Views/Task/PausedTasks_Partial.cshtml
@model BuildingFacilityManager.ViewModels.TaskViewModel

<h3>Paused Tasks</h3>

<div class="thumbnail">

    <div class="caption">
        <table class="table table-hover table-bordered" id="PausedTasksTable">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Description</th>
                    <th>Inspector</th>
                    <th>Status</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Periodic Inspection</th>
                    <th>Inspection Type</th>
                    <th>Location</th>
                    <th>Inspection Notes</th>
                    <th>Actions</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var task in Model.PausedInspectionTasks)
                {

                    <tr id="id-@task.Id">

                        <td>
                            @task.Id
                        </td>
                        <td>
                            @task.Description
                        </td>
                        <td>
                            @{
                                if (task.Inspector != null)
                                {
                                    @task.Inspector.Fullname

                                }

                            }
                        </td>
                        <td>
                            @task.InspectionStatus

                        </td>
                        <td>
                            @task.StartDate
                        </td>
                        <td>
                            @task.EndDate
                        </td>
                        <td>
                            @task.PeriodicInspection
                        </td>
                        <td>
                            @task.InspectionType
                        </td>
                        <td>
                            @{
                                if (@task.StoreyInspection != null)
                                {
                                    @task.StoreyInspection.Label

                                }

                            }
                        </td>
                        <td>
                            @task.InspectionNotes
                        </td>
                        <td>

                            <button type="button" title="Change Status" style="background-color: skyblue; background-repeat: no-repeat; border: none;cursor: pointer; overflow: hidden; outline: none;" data-toggle="modal" data-target="#Change-Status" onclick="TaskIdForStatusChange(@task.Id)">
                                <span class="far fa-edit" aria-hidden="true"></span>
                            </button>


                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BuildingFacilityManager/Areas/Admin/Views/Task/ScheduledTasks_Partial.cshtml
@model BuildingFacilityManager.ViewModels.TaskViewModel

<h3>Scheduled Tasks</h3>

<div class="thumbnail">

    <div class="caption">
        <table class="table table-hover table-bordered" id="ScheduledTasksTable">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Description</th>
                    <th>Inspector</th>
                    <th>Status</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Periodic Inspection</th>
                    <th>Inspection Type</th>
                    <th>Location</th>
                    <th>Inspection Notes</th>
                    <th>Actions</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var task in Model.ScheduledInspectionTasks)
                {

                    <tr id="id-@task.Id">

                        <td>
                            @task.Id
                        </td>
                        <td>
                            @task.Description
                        </td>
                        <td>
                            @{
                                if (task.Inspector != null)
                                {
                                    @task.Inspector.Fullname

                                }

                            }
                        </td>
                        <td>
                            @task.InspectionStatus

                        </td>
                        <td>
                            @task.StartDate
                        </td>
                        <td>
                            @task.EndDate
                        </td>
                        <td>
                            @task.PeriodicInspection
                        </td>
                        <td>
                            @task.InspectionType
                        </td>
                        <td>
                            @{
                                if (@task.StoreyInspection != null)
                                {
                                    @task.StoreyInspection.Label

                                }

                            }
                        </td>
                        <td>
                            @task.InspectionNotes
                        </td>
                        <td>

                            <button type="button" title="Change Status" style="background-color: skyblue; background-repeat: no-repeat; border: none;cursor: pointer; overflow: hidden; outline: none;" data-toggle="modal" data-target="#Change-Status" onclick="TaskIdForStatusChange(@task.Id)">
                                <span class="far fa-edit" aria-hidden="true"></span>
                            </button>


                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BuildingFacilityManager/Areas/Admin/Views/Task/TodaysTasks_Partial.cshtml
@model BuildingFacilityManager.ViewModels.TaskViewModel

<h3>Today's Inspection Tasks</h3>

<div class="thumbnail">

    <div class="caption">
        <table class="table table-hover table-bordered" id="TodayTasksTable">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Description</th>
                    <th>Inspector</th>
                    <th>Status</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Periodic Inspection</th>
                    <th>Inspection Type</th>
                    <th>Location</th>
                    <th>Inspection Notes</th>
                    <th>Actions</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var task in Model.TodayInspectionTasks)
                {

                <tr id="id-@task.Id">

                    <td>
                        @task.Id
                    </td>
                    <td>
                        @task.Description
                    </td>
                    <td>
                        @{
                            if (task.Inspector != null)
                            {
                                @task.Inspector.Fullname

                            }

                        }
                    </td>
                    <td>
                        @task.InspectionStatus

                    </td>
                    <td>
                        @task.StartDate
                    </td>
                    <td>
                        @task.EndDate
                    </td>
                    <td>
                        @task.PeriodicInspection
                    </td>
                    <td>
                        @task.InspectionType
                    </td>
                    <td>
                        @{
                            if (@task.StoreyInspection != null)
                            {
                                @task.StoreyInspection.Label

                            }

                        }
                    </td>
                    <td>
                        @task.InspectionNotes
                    </td>
                    <td>

                        <button type="button" title="Change Status" style="background-color: skyblue; background-repeat: no-repeat; border: none;cursor: pointer; overflow: hidden; outline: none;" data-toggle="modal" data-target="#Change-Status" onclick="TaskIdForStatusChange(@task.Id)">
                            <span class="far fa-edit" aria-hidden="true"></span>
                        </button>


                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>