BuildingFacilityManager/Models/Work Order/Enums/WorkOrderType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BuildingFacilityManager.Models.Work_Order.Enums
{
    public enum WorkOrderType
    {
        Calibration = 1,

        [Display(Name = "Corrective Maintenance")]
        CorrectiveMaintenance = 2,

        [Display(Name = "Emergency Maintenance")]
        EmergencyMaintenance = 3,

        [Display(Name = "Event Report")]
        EventReport = 4,

        [Display(Name = "Preventive Maintenance")]
        PreventiveMaintenance = 5,

        DownTime = 6,

        [Display(Name = "Service Request")]
        ServiceRequest = 7,

        [Display(Name = "General Maintenance")]
        GeneralMaintenance = 8

    }
}

BuildingFacilityManager/Models/Work Order/WorkOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using BuildingFacilityManager.Models.Assets;
using BuildingFacilityManager.Models.Purchase_Orders;
using BuildingFacilityManager.Models.Work_Order.Enums;

namespace BuildingFacilityManager.Models.Work_Order
{
    public class WorkOrder
    {
        public int Id { get; set; }
        [Required]
        public string Description { get; set; }
        public WorkOrderStatus WorkOrderStatus { get; set; }
        public DateTime? Date { get; set; }

        public WorkOrderType? WorkOrderType { get; set; }

        public Asset Asset { get; set; }
        [ForeignKey("Asset")]
        public int AssetId { get; set; }


        public ApplicationUser Reporter { get; set; }
        [ForeignKey("Reporter")]
        public string ReporterId { get; set; }


        public ApplicationUser Fixer { get; set; }
        [ForeignKey("Fixer")]
        public string FixerId { get; set; }

        public string FixerNotes { get; set; }
        public string PurchaseRequestNotes { get; set; }

        public ICollection<PurchaseOrder> PurchaseOrders { get; set; }


        /*
     1-   Attachments Property
     
         */


        /*
         
        1- Run end 2 end Tests
           2- New Rule (Fixer Manager)
           3- Assign of Work Orders to a Fixer is based on the department ( Type of Asset )
           4- Assign of Work Orders is based on Availability and Shift type ( Night or Today ) 
           5- Split the Work Order to ( Internal Tasks , Associate Materials, Tools and Services )
           
           

         */
    }
}

BuildingFacilityManager/ViewModels/WorkOrderViewModel.cs
using System.Collections.Generic;
using BuildingFacilityManager.Models;
using BuildingFacilityManager.Models.Assets;
using BuildingFacilityManager.Models.Building_Models;
using BuildingFacilityManager.Models.Work_Order;

namespace BuildingFacilityManager.ViewModels
{
    public class WorkOrderViewModel
    {
        public WorkOrder WorkOrder { get; set; }
        public List<WorkOrder> WorkOrders { get; set; }
        public List<Asset> Assets { get; set; }
        public List<Storey> Stories { get; set; }
        public List<Space> Spaces { get; set; }
        public Asset Asset { get; set; }
        public List<ApplicationUser> Users { get; set; }
        public List<ApplicationUser> Fixers { get; set; }
    }
}

BuildingFacilityManager/Areas/Admin/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using BuildingFacilityManager.Controllers;
using BuildingFacilityManager.Models;
using BuildingFacilityManager.Models.Work_Order;
using BuildingFacilityManager.ViewModels;

namespace BuildingFacilityManager.Areas.Admin.Controllers
{
    public class WorkOrderController : AdminAuthorizationController
    {
        private readonly ApplicationDbContext _context;

        public WorkOrderController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            _context.Dispose();

        }

        // GET: Admin/WorkOrder
        public ActionResult Index()
        {
            var workModel = new WorkOrderViewModel()
            {
                WorkOrders = _context.WorkOrders
                    .Include(w => w.Reporter)
                    .Include(w => w.Fixer)
                    .Include(w=>w.Asset)
                    .Include(w=>w.Asset.Space)
                    .Include(w=>w.Asset.Space.Storey)
                    .ToList(),
                Assets = _context.Assets.ToList(),
                Spaces = _context.Spaces.ToList(),
                Stories = _context.Stories.ToList(),
                Users = _context.Users.ToList(),
                Fixers = _context.Users.Where(u => u.Roles.Any(r => r.RoleId == "3")).ToList()
            };
            return View(workModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignWorkOrderToFixer(WorkOrder workOrder)
        {
            var myWork = _context.WorkOrders.SingleOrDefault(w => w.Id == workOrder.Id);
            if (myWork != null && workOrder.FixerId != null) myWork.FixerId = workOrder.FixerId;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeStatusWorkOrder(WorkOrder workOrder)
        {
            var myWork = _context.WorkOrders.SingleOrDefault(w => w.Id == workOrder.Id);
            if (myWork != null && workOrder.WorkOrderStatus != 0) myWork.WorkOrderStatus = workOrder.WorkOrderStatus;

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult AddWork(WorkOrder workOrder)
        {
            var workModel = new WorkOrderViewModel()
            {
                WorkOrders = _context.WorkOrders
                    .Include(w => w.Reporter)
                    .Include(w => w.Fixer)
                    .Include(w => w.Asset)
                    .Include(w => w.Asset.Space)
                    .Include(w => w.Asset.Space.Storey)
                    .ToList(),
                Assets = _context.Assets.ToList(),
                Spaces = _context.Spaces.ToList(),
                Stories = _context.Stories.ToList(),
                Fixers = _context.Users.Where(u => u.Roles.Any(r => r.RoleId == "3")).ToList()

            };

            if (workOrder.Description != null && workOrder.WorkOrderStatus != 0 && workOrder.AssetId != 0 )
            {
                _context.WorkOrders.Add(workOrder);
                _context.SaveChanges();
                var workMod = new WorkOrderViewModel()
                {
                    WorkOrders = _context.WorkOrders
                        .Include(w => w.Reporter)
                        .Include(w => w.Fixer)
                        .Include(w => w.Asset)
                        .Include(w => w.Asset.Space)
                        .Include(w => w.Asset.Space.Storey)
                        .ToList(),
                    Assets = _context.Assets.ToList(),
                    Spaces = _context.Spaces.ToList(),
                    Stories = _context.Stories.ToList(),
                    Fixers = _context.Users.Where(u => u.Roles.Any(r => r.RoleId == "3")).ToList()

                };
                return View("Index", workMod);

            }
            return View("Index",workModel);
        }

       
    }
}

BuildingFacilityManager/Areas/Inspector/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using BuildingFacilityManager.Controllers;
using BuildingFacilityManager.Models;
using BuildingFacilityManager.Models.Work_Order;
using BuildingFacilityManager.ViewModels;

namespace BuildingFacilityManager.Areas.Inspector.Controllers
{
    public class WorkOrderController : InspectorAuthorizationController
    {
        private readonly ApplicationDbContext _context;

        public WorkOrderController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            _context.Dispose();

        }

        // GET: Admin/WorkOrder
        public ActionResult Index()
        {
            var workModel = new WorkOrderViewModel()
            {
                WorkOrders = _context.WorkOrders.Include(w => w.Asset)
                    .Include(w => w.Asset.Space)
                    .Include(w => w.Asset.Space.Storey)
                    .ToList(),
                Assets = _context.Assets.ToList(),
                Spaces = _context.Spaces.ToList()
            };
            return View(workModel);
        }

        public ActionResult AddWork(WorkOrder workOrder)
        {

            var workModel = new WorkOrderViewModel()
            {
                WorkOrders = _context.WorkOrders.Include(w => w.Asset)
                    .Include(w => w.Asset.Space)
                    .Include(w => w.Asset.Space.Storey)
                    .ToList(),
                Assets = _context.Assets.ToList(),
                Spaces = _context.Spaces.ToList(),
            };

            if (workOrder.Description != null && workOrder.WorkOrderStatus != 0 && workOrder.AssetId != 0)
            {
                var user = User;
                _context.WorkOrders.Add(workOrder);
                _context.SaveChanges();
                var workMod = new WorkOrderViewModel()
                {
                    WorkOrders = _context.WorkOrders.Include(w => w.Asset)
                        .Include(w => w.Asset.Space)
                        .Include(w => w.Asset.Space.Storey)
                        .ToList(),
                    Assets = _context.Assets.ToList(),
                    Spaces = _context.Spaces.ToList()
                };
                return View("Index", workMod);

            }

            return View("Index", workModel);

        }

        
    }
}

BuildingFacilityManager/Areas/Org/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuildingFacilityManager.Controllers;
using BuildingFacilityManager.Models;
using BuildingFacilityManager.ViewModels;

namespace BuildingFacilityManager.Areas.Org.Controllers
{
    public class WorkOrderController : OrgAuthorizationController
    {
        private readonly ApplicationDbContext _context;

        public WorkOrderController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            _context.Dispose();

        }

        // GET: Org/WorkOrder
        public ActionResult Index()
        {
            var workModel = new WorkOrderViewModel()
            {
                WorkOrders = _context.WorkOrders.Include(w => w.Asset)
                    .Include(w => w.Asset.Space)
                    .Include(w => w.Asset.Space.Storey)
                    .ToList(),
                Assets = _context.Assets.ToList(),
                Spaces = _context.Spaces.ToList()
            };
            return View(workModel);
        }

        public ActionResult CompleteOrder()
        {
            throw new NotImplementedException();
        }
    }
}

BuildingFacilityManager/Areas/Inspector/Views/WorkOrder/Add_WorkOrder_Inspector_Partial.cshtml
@using BuildingFacilityManager.Models.Assets.Enums
@using BuildingFacilityManager.Models.Work_Order.Enums
@model BuildingFacilityManager.ViewModels.WorkOrderViewModel


@{

    using (Ajax.BeginForm("AddWork", "WorkOrder", new AjaxOptions()
    {
        Confirm = "Are you Sure ?",
        HttpMethod = "Post",
        UpdateTargetId = "Work-table",
        InsertionMode = InsertionMode.InsertAfter,
        OnSuccess = "$('.close').click();"

    }))
    {


        <div class="modal fade" id="myModal-AddWork" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Add a new Work Order</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            @Html.HiddenFor(s => s.WorkOrder.Id)

                        </div>

                        <div>
                            @Html.LabelFor(e => e.WorkOrder.Description)
                            @Html.TextBoxFor(e => e.WorkOrder.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.WorkOrder.Description)

                        </div>

                        <div>
                            @Html.LabelFor(e => e.WorkOrder.WorkOrderStatus)
                            @Html.DropDownListFor(e => e.WorkOrder.WorkOrderStatus, EnumHelper.GetSelectList(typeof(WorkOrderStatus)) ,
                                "Select Type", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.WorkOrder.WorkOrderStatus)

                        </div>

                        <div>
                            @Html.LabelFor(e => e.WorkOrder.AssetId)
                            @Html.DropDownListFor(e => e.WorkOrder.AssetId,  new SelectList(Model.Assets, "Id","Label"),
                                "Select Type", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.WorkOrder.AssetId)

                        </div>


                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>

        </div>

    }
}


@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

}

BuildingFacilityManager/Areas/Inspector/Views/WorkOrder/Index.cshtml
@model BuildingFacilityManager.ViewModels.WorkOrderViewModel

@{
    ViewBag.Title = "Work Orders";
    Layout = "../Shared/_Layout.cshtml";
}

<h2>Work Orders</h2>

@Html.Partial("WorkOrder_Inspector_Partial")
@Html.Partial("Add_WorkOrder_Inspector_Partial")

BuildingFacilityManager/Areas/Inspector/Views/WorkOrder/WorkOrder_Inspector_Partial.cshtml
@model BuildingFacilityManager.ViewModels.WorkOrderViewModel


<button type="button" class="btn btn-success" style="float: right" data-toggle="modal" data-target="#myModal-AddWork">
    Add
</button>

<table class="table table-hover table-striped">
    <thead>
    <tr>
        <th>Id</th>
        <th>Description</th>
        <th>Status</th>
        <th>Asset</th>
        <th>Location</th>
        <th>Storey</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var work in Model.WorkOrders)
    {

        <tr id="id-@work.Id">
                
            <td>
                @work.Id
            </td>
            <td>
                @work.Description
            </td>
            <td>
                @work.WorkOrderStatus
            </td>
            <td>
                @work.Asset.Label
            </td>
            <td>
                @work.Asset.Space.Label
            </td>
            <td>
                @work.Asset.Space.Storey.Label
            </td>
        </tr>
    }
    </tbody>
</table>