BuildingFacilityManager/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using BuildingFacilityManager.Controllers;
using BuildingFacilityManager.Models;
using BuildingFacilityManager.Models.Tasks.Enums;
using BuildingFacilityManager.Models.Work_Order.Enums;
using BuildingFacilityManager.ViewModels;

namespace BuildingFacilityManager.Areas.Admin.Controllers
{
    public class DashboardController : AdminAuthorizationController
    {
        private readonly ApplicationDbContext _context;


        public DashboardController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            _context.Dispose();
        }


        public ActionResult Index()
        {
            //ViewBag.HealthAlert = Convert.ToInt32(TempData["HealthAlert"]);
            //ViewBag.AssetId = Convert.ToInt32(TempData["AssetId"]);

            var today = DateTime.Today;
            var todayLastWeek = today.AddDays(-7);
            //var todayLastWeek = today.(-7);
            var tomorrow = today.AddDays(1);
            var yesterday = today.AddDays(-1);

            int health = 100;
            int id = 0;
            var assetAffected = _context.Assets.Where(a => a.HealthMeasurement < 100).ToList();
            var minAffectedHealth = new List<int>();
            foreach (var asset in assetAffected)
            {
                if (asset.HealthMeasurement != null)
                {
                    minAffectedHealth.Add((int)asset.HealthMeasurement);
                    health = minAffectedHealth.Min();
                    id = asset.Id;
                }
                
            }
            var model = new DashBoardViewModel()
            {
                WorkOrders = _context.WorkOrders.Where(w=>
                        DbFunctions.TruncateTime(w.Date)
                        == DbFunctions.TruncateTime(DateTime.Today)

                             //w => w.Date >= DateTime.Today

                             )
                   .Include(w => w.Asset)
                   .Include(w => w.Asset.Space)
                   .Include(w => w.Asset.Space.Storey).ToList(),

                TodayActiveWorkOrders = _context.WorkOrders.Where(w =>
                DbFunctions.TruncateTime(w.Date)
                == DbFunctions.TruncateTime(DateTime.Today)

                &&

                w.WorkOrderStatus == WorkOrderStatus.Active

                )
                .Include(w => w.Asset)
                .Include(w => w.Asset.Space)
                .Include(w => w.Asset.Space.Storey).ToList(),

                TodayCompletedWorkOrders = _context.WorkOrders.Where(w =>
                DbFunctions.TruncateTime(w.Date)
                == DbFunctions.TruncateTime(DateTime.Today)

                &&

                w.WorkOrderStatus == WorkOrderStatus.Completed

                )
                .Include(w => w.Asset)
                .Include(w => w.Asset.Space)
                .Include(w => w.Asset.Space.Storey).ToList(),


                TodayInProgressWorkOrders = _context.WorkOrders.Where(w =>
                        DbFunctions.TruncateTime(w.Date)
                        == DbFunctions.TruncateTime(DateTime.Today)

                        &&

                        w.WorkOrderStatus == WorkOrderStatus.InProgress

                    )
                    .Include(w => w.Asset)
                    .Include(w => w.Asset.Space)
                    .Include(w => w.Asset.Space.Storey).ToList(),

                TodayWaitingPurchaseWorkOrders = _context.WorkOrders.Where(w =>
                        DbFunctions.TruncateTime(w.Date)
                        == DbFunctions.TruncateTime(DateTime.Today)

                        &&

                        w.WorkOrderStatus == WorkOrderStatus.WaitingPurchase

                    )
                    .Include(w => w.Asset)
                    .Include(w => w.Asset.Space)
                    .Include(w => w.Asset.Space.Storey).ToList(),

                TodayInstalledAssets = _context.Assets.Where(a =>
                            DbFunctions.TruncateTime(a.InstallationDate)
                            == DbFunctions.TruncateTime(DateTime.Today)
                        )


                    .Include(a => a.Space)
                    .Include(a => a.RelatedAssets)
                    .ToList(),
                DashBoardUsers = _context.Users.ToList(),
               TodayInspectionTasks = _context.InspectionTasks
                    .Where(t =>
                        DbFunctions.TruncateTime(t.StartDate)
                        == DbFunctions.TruncateTime(today) 
                        ||
                        DbFunctions.TruncateTime(today)
                        <= DbFunctions.TruncateTime(t.EndDate) &&
                        DbFunctions.TruncateTime(today)
                        >= DbFunctions.TruncateTime(t.StartDate)
                        /*  today <= t.EndDate && today >= t.StartDate */
                        && t.PeriodicInspection == PeriodicInspection.Daily
                       

                        ||

                        // Stupid Code starts from Here !

                        today.Day == (t.StartDate.Value.Day + 7) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                       
                        ||
                        today.Day == (t.StartDate.Value.Day + 14) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                       
                        ||
                        today.Day == (t.StartDate.Value.Day + 21) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                     
                        ||
                        today.Day == (t.StartDate.Value.Day + 28) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                       
                    )

                    .Include(t => t.StoreyInspection)
                    .ToList(),
                TodayInspectionTasksActive  = _context.InspectionTasks
                .Where(t =>
                DbFunctions.TruncateTime(t.StartDate)
                == DbFunctions.TruncateTime(today) && t.InspectionStatus == InspectionStatus.Active
                ||
                DbFunctions.TruncateTime(today)
                <= DbFunctions.TruncateTime(t.EndDate) &&
                DbFunctions.TruncateTime(today)
                >= DbFunctions.TruncateTime(t.StartDate)
                /*  today <= t.EndDate && today >= t.StartDate */
                && t.PeriodicInspection == PeriodicInspection.Daily
                && t.InspectionStatus == InspectionStatus.Active

                ||

                // Stupid Code starts from Here !

                today.Day == (t.StartDate.Value.Day + 7) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                && t.InspectionStatus == InspectionStatus.Active
                ||
                today.Day == (t.StartDate.Value.Day + 14) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                && t.InspectionStatus == InspectionStatus.Active
                ||
                today.Day == (t.StartDate.Value.Day + 21) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                && t.InspectionStatus == InspectionStatus.Active
                ||
                today.Day == (t.StartDate.Value.Day + 28) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                && t.InspectionStatus == InspectionStatus.Active
                )

                .Include(t => t.StoreyInspection)
                .ToList(),

                TodayInspectionTasksCompleted = _context.InspectionTasks
                    .Where(t =>
                        DbFunctions.TruncateTime(t.StartDate)
                        == DbFunctions.TruncateTime(today) && t.InspectionStatus == InspectionStatus.Completed
                        ||
                        DbFunctions.TruncateTime(today)
                        <= DbFunctions.TruncateTime(t.EndDate) &&
                        DbFunctions.TruncateTime(today)
                        >= DbFunctions.TruncateTime(t.StartDate)
                        /*  today <= t.EndDate && today >= t.StartDate */
                        && t.PeriodicInspection == PeriodicInspection.Daily
                        && t.InspectionStatus == InspectionStatus.Completed

                        ||

                        // Stupid Code starts from Here !

                        today.Day == (t.StartDate.Value.Day + 7) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                        && t.InspectionStatus == InspectionStatus.Completed
                        ||
                        today.Day == (t.StartDate.Value.Day + 14) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                        && t.InspectionStatus == InspectionStatus.Completed
                        ||
                        today.Day == (t.StartDate.Value.Day + 21) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                        && t.InspectionStatus == InspectionStatus.Completed
                        ||
                        today.Day == (t.StartDate.Value.Day + 28) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                        && t.InspectionStatus == InspectionStatus.Completed
                    )

                    .Include(t => t.StoreyInspection)
                    .ToList(),
                TodayInspectionTasksPartiallyCompleted = _context.InspectionTasks
                    .Where(t =>
                        DbFunctions.TruncateTime(t.StartDate)

BuildingFacilityManager/Areas/Inspector/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuildingFacilityManager.Controllers;
using BuildingFacilityManager.Models;
using BuildingFacilityManager.Models.Tasks.Enums;
using BuildingFacilityManager.Models.Work_Order.Enums;
using BuildingFacilityManager.ViewModels;
using Microsoft.AspNet.Identity;

namespace BuildingFacilityManager.Areas.Inspector.Controllers
{
    public class DashboardController : InspectorAuthorizationController
    {
        private readonly ApplicationDbContext _context;

        public DashboardController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            _context.Dispose();
        }


        public ActionResult Index()
        {
            var today = DateTime.Today;
            var todayLastWeek = today.AddDays(-7);
            //var todayLastWeek = today.(-7);
            var tomorrow = today.AddDays(1);
            var yesterday = today.AddDays(-1);
            var userId = User.Identity.GetUserId();

            var model = new DashBoardViewModel()
            {

                TodayInspectionTasks =  _context.InspectionTasks
                    .Where(t =>
                        DbFunctions.TruncateTime(t.StartDate)
                        == DbFunctions.TruncateTime(today) && userId  == t.InspectorId
                        //t => t.StartDate >= today && t.StartDate < tomorrow
                        ||
                        DbFunctions.TruncateTime(today)
                        <= DbFunctions.TruncateTime(t.EndDate) &&
                        DbFunctions.TruncateTime(today)
                        >= DbFunctions.TruncateTime(t.StartDate)
                        /*  today <= t.EndDate && today >= t.StartDate */
                        && t.PeriodicInspection == PeriodicInspection.Daily
                        && userId == t.InspectorId

                        ||

                        // Stupid Code starts from Here !

                        today.Day == (t.StartDate.Value.Day + 7) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                        && userId == t.InspectorId
                        ||
                        today.Day == (t.StartDate.Value.Day + 14) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                        && userId == t.InspectorId
                        ||
                        today.Day == (t.StartDate.Value.Day + 21) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                        && userId == t.InspectorId
                        ||
                        today.Day == (t.StartDate.Value.Day + 28) && today <= t.EndDate && t.PeriodicInspection == PeriodicInspection.Weekly
                        && userId == t.InspectorId
                        )

                    .Include(t => t.StoreyInspection)
                    .ToList(),
                ScheduledInspectionTasks = _context.InspectionTasks
                    .Where(t => t.StartDate >= tomorrow && userId == t.InspectorId)
                    .Include(t => t.Inspector)
                    .Include(t => t.StoreyInspection)
                    .ToList(),
                MyCreatedWorkOrdersToday = _context.WorkOrders.Where(w=>w.ReporterId == userId && 
                                                                        DbFunctions.TruncateTime(w.Date)
                                                                        == DbFunctions.TruncateTime(today))
                    .Include(w => w.Reporter)
                    .Include(w => w.Fixer)
                    .Include(w => w.Asset)
                    .Include(w => w.Asset.Space)
                    .Include(w => w.Asset.Space.Storey)
                    .ToList(),
                DashBoardUsers = _context.Users.ToList(),
                
                
            };
            return View(model);
        }

    }
}

BuildingFacilityManager/Areas/Org/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuildingFacilityManager.Controllers;
using BuildingFacilityManager.Models;
using BuildingFacilityManager.Models.Work_Order;
using BuildingFacilityManager.ViewModels;
using Microsoft.AspNet.Identity;

namespace BuildingFacilityManager.Areas.Org.Controllers
{
    public class DashboardController : OrgAuthorizationController
    {
        private readonly ApplicationDbContext _context;

        public DashboardController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            var today = DateTime.Today;
            var todayLastWeek = today.AddDays(-7);
            //var todayLastWeek = today.(-7);
            var tomorrow = today.AddDays(1);
            var yesterday = today.AddDays(-1);
            var userId = User.Identity.GetUserId();


            var model = new DashBoardViewModel()
            {
                DashBoardUsers = _context.Users.ToList(),
                MyAssignedWorkOrdersToday = _context.WorkOrders.Where(w => w.FixerId == userId &&
                      DbFunctions.TruncateTime(w.Date)
                     == DbFunctions.TruncateTime(today))
                    .Include(w => w.Asset)
                    .Include(w => w.Asset.Space)
                    .Include(w => w.Asset.Space.Storey)
                    .ToList(),

                MyAssignedWorkOrdersTotal = _context.WorkOrders.Where(w => w.FixerId == userId)
                    .Include(w => w.Asset)
                    .Include(w => w.Asset.Space)
                    .Include(w => w.Asset.Space.Storey)
                    .ToList()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeStatusWorkOrder(WorkOrder workOrder)
        {
            var myWork = _context.WorkOrders.SingleOrDefault(w => w.Id == workOrder.Id);
            if (myWork != null && workOrder.WorkOrderStatus != 0) myWork.WorkOrderStatus = workOrder.WorkOrderStatus;
            if (myWork != null && workOrder.FixerNotes != null) myWork.FixerNotes = workOrder.FixerNotes;

            _context.SaveChanges();

            return RedirectToAction("Index");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PurchaseRequest(WorkOrder workOrder)
        {
            var myWork = _context.WorkOrders.SingleOrDefault(w => w.Id == workOrder.Id);
            if (myWork != null && workOrder.WorkOrderStatus != 0) myWork.WorkOrderStatus = workOrder.WorkOrderStatus;
            if (myWork != null && workOrder.PurchaseRequestNotes != null) myWork.PurchaseRequestNotes = workOrder.PurchaseRequestNotes;

            _context.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

BuildingFacilityManager/Areas/Purchase/Views/Dashboard/AddPurchaseOrder_Partial.cshtml
@model BuildingFacilityManager.ViewModels.DashBoardViewModel



@{

    using (Ajax.BeginForm("AddPurchaseOrder", "Dashboard", new AjaxOptions()
    {
        Confirm = "Are you Sure ?",
        HttpMethod = "Post",
        OnSuccess = "$('.close').click();"

    }))
    {


        <div class="modal fade" id="AddPurchaseOrder" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Add a new Purchase Order</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <input id="work-Id-purchase" name="PurchaseOrder.WorkOrderId" type="hidden" value="">


                        </div>

                        <div class="form-group">
                            @Html.LabelFor(e => e.PurchaseOrder.Description)
                            @Html.TextAreaFor(e => e.PurchaseOrder.Description, new { @class = "form-control", style = "width: 100%; max-width: 100%;" })
                            @Html.ValidationMessageFor(e => e.PurchaseOrder.Description)

                        </div>


                        <div class="form-group">
                            @Html.LabelFor(e => e.PurchaseOrder.PurchaseDateTime)
                            @Html.TextBoxFor(c => c.PurchaseOrder.PurchaseDateTime, new { @class = "datepicker form-control", @type = "datetime-local" })
                            @Html.ValidationMessageFor(e => e.PurchaseOrder.PurchaseDateTime)

                        </div>


                        <div class="form-group">
                            @Html.LabelFor(e => e.PurchaseOrder.Cost)
                            @Html.TextBoxFor(e => e.PurchaseOrder.Cost, new { @class = "form-control", @placeholder= "Enter the Cost in EGP"})
                            @Html.ValidationMessageFor(e => e.PurchaseOrder.Cost)

                        </div>

                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Add" class="btn btn-primary" />
                </div>
            </div>

        </div>

    }
    
}


<script>
    let WorkIdForPurchase;

    function WorkIdForNewPurchaseOrder(id) {
        WorkIdForPurchase = id;
        document.getElementById("work-Id-purchase").value = WorkIdForPurchase;

    }
</script>

BuildingFacilityManager/Areas/Purchase/Views/Dashboard/AllCompletedPurchaseOrders_Partial.cshtml
@model BuildingFacilityManager.ViewModels.DashBoardViewModel

<hr />
<br />
<h3>All Completed Purchase Work Orders</h3>

<div class="thumbnail">

    <div class="caption">
        <table class="table table-hover table-bordered" id="CompletedPurchaseToday">
            <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Date</th>
                <th>Cost</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var purchaseOrder in Model.AllCompletedPurchaseOrders)
            {

                <tr id="id-@purchaseOrder.Id">

                    <td>
                        @purchaseOrder.Id
                    </td>
                    <td>
                        @purchaseOrder.Description
                    </td>
                    <td>

                        @purchaseOrder.PurchaseDateTime
                    </td>
                    <td>
                        @purchaseOrder.Cost

                    </td>
                    <td>
                        @purchaseOrder.WorkOrderId
                    </td>
                    
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

BuildingFacilityManager/Areas/Purchase/Views/Dashboard/ChangeStatus_Partial.cshtml
@using BuildingFacilityManager.Models.Work_Order.Enums
@using Microsoft.AspNet.Identity
@model BuildingFacilityManager.ViewModels.DashBoardViewModel

@{

    using (Html.BeginForm("ChangeStatusWorkOrder", "Dashboard", new AjaxOptions()
    {
        HttpMethod = "Post",
        OnSuccess = "$('.close').click();"
    }))
    {


        <div class="modal fade" id="Change-Status" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Change Work Order Status</h4>
                    </div>
                    <div class="modal-body">
                        <input id="work-Id-Status" name="WorkOrder.Id" type="hidden" value="">
                        <div>
                            @Html.LabelFor(e => e.WorkOrder.WorkOrderStatus)
                            @Html.DropDownListFor(e => e.WorkOrder.WorkOrderStatus, EnumHelper.GetSelectList(typeof(WorkOrderStatus)) ,
                                "Select Type", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.WorkOrder.WorkOrderStatus)

                        </div>
                       
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Change Status" class="btn btn-primary" />
                </div>
            </div>

        </div>

    }
}



<script>
    let statusId;

    function WorkIdForStatusChange(id) {
        statusId = id;
        document.getElementById("work-Id-Status").value = statusId;

    }
</script>

BuildingFacilityManager/Areas/Purchase/Views/Dashboard/ChangeTaskStatus_Partial.cshtml
@using BuildingFacilityManager.Models.Tasks.Enums
@model BuildingFacilityManager.ViewModels.DashBoardViewModel

@{

    using (Html.BeginForm("ChangeInspectionTaskStatus", "Task", new AjaxOptions()
    {
        HttpMethod = "Post",
        OnSuccess = "$('.close').click();"

    }))
    {


        <div class="modal fade" id="Change-Status" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Change Task Status</h4>
                    </div>
                    <div class="modal-body">
                        <input id="task-Id-Status" name="InspectionTask.Id" type="hidden" value="">

                        <div>
                            @Html.LabelFor(e => e.InspectionTask.InspectionStatus)
                            @Html.DropDownListFor(e => e.InspectionTask.InspectionStatus, EnumHelper.GetSelectList(typeof(InspectionStatus)) ,
                                "Select Type", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.InspectionTask.InspectionStatus)

                        </div>
                        @Html.LabelFor(e => e.InspectionTask.InspectionNotes)
                        @Html.TextAreaFor(e => e.InspectionTask.InspectionNotes, new { @class = "form-control", style = "width: 100%; max-width: 100%;" })
                        @Html.ValidationMessageFor(e => e.InspectionTask.InspectionNotes)

                        <div>

                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Change Status" class="btn btn-primary" />
                </div>
            </div>

        </div>

    }
}



<script>
    let statusId;

    function TaskIdForStatusChange(id) {
        statusId = id;
        document.getElementById("task-Id-Status").value = statusId;

    }
</script>

BuildingFacilityManager/Areas/Purchase/Views/Dashboard/IconCardsTodayStats_Partial.cshtml
@model BuildingFacilityManager.ViewModels.DashBoardViewModel

<br/>


<div class="row">
  
    
    <div class="col-sm-4 mb-3">
        <div class="card text-white bg-danger o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-cart-plus"></i>
                </div>
                <div class="mr-5">(@Model.TodayWaitingPurchaseWorkOrders.Count) Today's Waiting Purchase Orders</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="#workOrderTableToday">
                <span class="float-left">View Details</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
    
    <div class="col-sm-4 mb-3">
        <div class="card text-white bg-success o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-shopping-cart"></i>
                </div>
                <div class="mr-5">(@Model.TodayCompletedPurchaseOrders.Count) Today's Completed Purchase Orders</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="#workOrderTableAll">
                <span class="float-left">View Details</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>

</div>

BuildingFacilityManager/Areas/Purchase/Views/Dashboard/Index.cshtml
@model BuildingFacilityManager.ViewModels.DashBoardViewModel
@{
    Layout = "~/Areas/Purchase/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Dashboard";
}
<style type="text/css">
    .col-xl-3.col-sm-6.mb-3 {
        padding-bottom: 5px;
    }
</style>

@Html.Partial("IconCardsTodayStats_Partial")


@Html.Partial("ChangeStatus_Partial")

@Html.Partial("AddPurchaseOrder_Partial")

@Html.Partial("MyTodayWaitingPurchaseOrders_Partial")

@Html.Partial("MyTodayCompletedPurchaseOrders_Partial")

@*@Html.Partial("AllCompletedPurchaseOrders_Partial")*@


@section styles {
    @Styles.Render("~/Content/sb-adminCustom.css")
    @Styles.Render("~/Content/fonts/all.css")
}

@section Scripts {

    @Scripts.Render("~/Scripts/jquery.easing.min.js");
    @Scripts.Render("~/bundles/jquery");
    @Scripts.Render("~/bundles/charts");
    <script>
        $(document).ready(function () {
            $("#CompletedPurchaseToday").DataTable();
            $("#WaitingPurchaseToday").DataTable();
        });

    </script>
}

BuildingFacilityManager/Areas/Purchase/Views/Dashboard/PurchaseRequest_Partial.cshtml
@using BuildingFacilityManager.Models.Work_Order.Enums
@using Microsoft.AspNet.Identity
@model BuildingFacilityManager.ViewModels.DashBoardViewModel

@{

    using (Html.BeginForm("PurchaseRequest", "Dashboard", new AjaxOptions()
    {
        HttpMethod = "Post",
        OnSuccess = "$('.close').click();"
    }))
    {


        <div class="modal fade" id="PurchaseRequest" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Create a Purchase Request</h4>
                    </div>
                    <div class="modal-body">
                        <input id="work-Id-purchase" name="WorkOrder.Id" type="hidden" value="">
                        <div>
                            @Html.LabelFor(e => e.WorkOrder.WorkOrderStatus)
                            @Html.DropDownListFor(e => e.WorkOrder.WorkOrderStatus, EnumHelper.GetSelectList(typeof(WorkOrderStatus)) ,
                                "Select Type", new { @class = "form-control" })
                            @Html.ValidationMessageFor(e => e.WorkOrder.WorkOrderStatus)

                        </div>
                        <div>
                            @Html.LabelFor(e => e.WorkOrder.PurchaseRequestNotes)
                            @Html.TextAreaFor(e => e.WorkOrder.PurchaseRequestNotes, new { @class = "form-control", style = "width: 100%; max-width: 100%;" })
                            @Html.ValidationMessageFor(e => e.WorkOrder.PurchaseRequestNotes)

                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Change Status" class="btn btn-primary" />
                </div>
            </div>

        </div>

    }
}



<script>
    let purchaseId;

    function purchaseRequestFunc(id) {
        purchaseId = id;
        document.getElementById("work-Id-purchase").value = purchaseId;

    }
</script>